# Filepath to store the file to or load it from
string filePath
---
# A status code that indicats the succes of the operation
uint8 succes

uint8 OK=0
uint8 ERROR_WRITING_FILE=1
uint8 ERROR_READING_FILE=2
