sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: points
    #//TODO enter correct values
    max_range: 2.0
    point_subsample: 1
    padding_offset: 0.1
    padding_scale: 0.1
    filtered_cloud_topic: filtered_cloud
