# The cucmber that needs to be harvested.
cucumber_msgs/Cucumber cucumber

# The desired dropoff location and rotation of the produce.
geometry_msgs/Pose dropLocation
---
# The result of the harvest action.
byte status

# Possible status codes for the harvest process.
byte OK = 0
byte ERROR = 1
byte GRAB_ERR = 2
byte VACU_ERR = 3
byte CUTT_ERR = 4
byte MOVE_ERR = 5

# Deprecated constants, do not use these!
byte DROP_ERR = 7
byte NOVAC_ERR = 8

